export const SONG_FIELD_NAMES = [
    "boss_1",
    "boss_2",
    "ending",
    "stage_1_1",
    "stage_1_2",
    "stage_2_1",
    "stage_3_1",
    "stage_4_1",
    "stage_4_2",
    "stage_5_1",
    "stage_6_1",
    "stage_6_2"
] as const;

export const STANDALONE_MUSIC_FIELD_NAMES = [
    "game_over",
    "map_1",
    "map_2",
    "map_3",
    "map_4",
    "prologue",
    "simon_killed",
    "stage_cleared",
    "dracula_dead"
] as const;

export const SOUND_EFFECT_FIELD_NAMES = [
    "advance_whip",
    "bat_killed",
    "bleep",
    "boss_hurt",
    "boss_killed_1",
    "boss_killed_2",
    "boss_killed_3",
    "breaks_wall",
    "crumble_sfx",
    "dog_killed",
    "door_opens_1",
    "door_opens_2",
    "gain_potion",
    "got_money",
    "heartbeat",
    "hit_candle",
    "killed_1",
    "killed_2",
    "killed_3",
    "killed_4",
    "killed_5",
    "lose_potion",
    "merman_spit",
    "one_up",
    "pressed_enter",
    "simon_hurt",
    "splash",
    "torch_breaks",
    "whip_1",
    "whip_2",
    "wing_flaps",
    "zombie_killed",
    "got_double",
    "kill_all_sfx",
    "simon_in_pit",
    "threw_dagger",
    "got_weapon",
    "used_holy_water",
    "spinning",
    "raven_killed",
    "ching",
    "snuffed",
    "medusa_head_killed",
    "stunned",
    "watch_tick",
    "twang",
    "large_bat_killed",
    "thunder",
    "fire_ball_shot",
    "dracula_to_bats",
    "lands"
] as const;
